### PR TITLE
Integrate code from raye-sailbot-web-app

### PR DESCRIPTION
**Pull request by jahn18**
### Description

Lays the groundwork for a functional web-app (e.g. added redux, setup the directory structure, etc.). As of now, the website  only tracks the boat's GPS coordinates on a map by polling the data from MongoDB. More features will be added later.  

### Verification

- Tested things locally. 

### Resources

- https://redux-toolkit.js.org/
- https://www.mongodb.com/atlas/database

### CODE REVIEW

**Review by patrick-5546 — COMMENTED** [review]
I am getting this error when opening the website
image
Any idea what might be happening?
This is the website dockerfile: https://github.com/UBCSailbot/sailbot_workspace/blob/main/.devcontainer/website/website.Dockerfile

**Comment by jahn18** [comment]
@patrick-5546 Can you tell me the steps you did to run this? Things seem ok on my end - the `react-google-maps` dependency should be included within the `package.json` file I pushed to this branch

**Comment by patrick-5546** [comment]
I fixed by running `npm install` in the container.

@jahn18 can you investigate whether this manual step is still needed after deleting package-lock.json? For example, add a dependency to package.json then rebuild the dev container then check if it has been installed.

**Comment by patrick-5546** [comment]
I'm getting this warning, is this expected?
image

**Comment by jahn18** [comment]
@patrick-554 Yup, for sure. I will investigate once I get back. 

Also, yes, that error is expected - a valid `GOOGLE_API_KEY` needs to be supplied in the env var file (we can get a free one using our sailbot account). I was using just my own key when testing locally.

**Comment by patrick-5546** [comment]
> a valid GOOGLE_API_KEY needs to be supplied in the env.local file (we can get a free one using our sailbot account)

How can I get one? I can use the software leads Google account and paste the API key in confluence

**Comment by patrick-5546** [comment]
Seems like committing package-lock.json is standard practice. Maybe we should document the process of adding a dependency and ensuring that the lockfile was updated

**Review by patrick-5546 — APPROVED** [review]

**Comment by jahn18** [comment]
@patrick-5546 To follow up on your comments: 

> How can I get one? I can use the software leads Google account and paste the API key in confluence. We could also update the README with this 

You can create an API Key by following the documentation here: https://developers.google.com/maps/documentation/javascript/cloud-setup 
(I'm specifically using the Maps JavaScript API package) 


To get started, you're going to have to first setup a **general project** to manage services, credentials, API keys, etc. and also **enable billing**.  Then you can move onto the next step under the header **Use API Keys**, which is where you can create an API key within the project you created. 

**Note on billing:** Google gives $200 credit for free and this refreshes every month. This means we can make about ~28,000 requests (or "map loads") per month using the API before they start charging us (more info can be found in the [docs](https://developers.google.com/maps/documentation/javascript/usage-and-billing#dynamic-maps)). 
- For development purposes, the monthly quota should be good enough, but we may need to consider paying once the website becomes live and it gets more traffic.
- If you happen to be curious about what is defined as a single "map load", it can be found here: https://developers.google.com/maps/faq#usage_mapload

> Seems like committing package-lock.json is standard practice. Maybe we should document the process of adding a dependency and ensuring that the lockfile was updated

I did some reading and you're right. I created a new issue for this here: https://github.com/UBCSailbot/website/issues/6

**Pull request merged**
