### PR TITLE
Added a header to index.tsx

### LINKED ISSUE #89: Add UBC Sailbot Header to Website
### Purpose

Adds a header to the website to signify that our website is of UBC Sailbot! 

### Changes

image

The blue header above is an example of what we want. It should include the UBC logo and the text "UBC Sailbot". 

~Add the header in this file: https://github.com/UBCSailbot/website/blob/main/pages/dashboard/index.tsx We're adding it to the dashboard page. To check your work, access the page `localhost:3005/dashboard`~ 

(UPDATE) Please add the header here: https://github.com/UBCSailbot/website/blob/main/pages/index.tsx#L26

You can check your work on the main page, so just `localhost:3005`

You can find the logo in the resources below.

### Resources

- UBC Sailbot Logo (blue): https://github.com/UBCSailbot/raye-sailbot-web-app/blob/master/front-end/src/Sailbot%2BLogo%2BNew.png
- UBC Sailbot Logo (white): https://github.com/UBCSailbot/raye-sailbot-web-app/blob/master/front-end/src/SailbotLogo.png
- Example code from previous website on how the header was implemented: [UBCSailbot/raye-sailbot-web-app@master/front-end/src/views/Dashboard/Dashboard/Dashboard.tsx#L31](https://github.com/UBCSailbot/raye-sailbot-web-app/blob/master/front-end/src/views/Dashboard/Dashboard/Dashboard.tsx#L31)

### PR DESCRIPTION
**Pull request by fyang151**
### Description

- Resolves #89

Added Header component to index.tsx
Created Header.tsx inside components
Added SailbotLogo.png inside public

### Verification

- there was some white space around the header, used negative margin to eliminate this, looking for more intuitive solution

### Resources

-

### CODE REVIEW

**Review by jahn18 — APPROVED** [review]
Solid work!

**Comment by jahn18** [comment]
Todo:

- Add the Header component to it's own directory `Header`. 
- Create a custom `.css` file for the styles used in the component (take a look at how https://github.com/UBCSailbot/website/blob/main/pages/style.module.css is used for reference) 
- If possible, make the header sticky and not use up vertical space.

**Review by jahn18 — CHANGES_REQUESTED** [review]
Very minor comments:
- You left a `console.log` in the code so that needs to be removed.
- The pipeline is failing because of lint checks. To fix this, you want to go into the docker desktop, click on the website container, go into the tab labelled `exec`, then run the commands `npm run format` and `npm run lint`. Then commit whatever files the linter has reformatted. 

Thanks for getting rid of the extra vertical scroll :)

**Comment by fyang151** [comment]
ohh right thanks john sry abt that ill fix that soon

**Review by jahn18 — APPROVED** [review]
Thanks, looks great!

**Pull request merged**
